### ISSUE TITLE
``help_description`` does not fully describe, where description is displayed

### ISSUE THREAD

**Issue by thet** [collective/plone.app.locales#124]
`help_description` text is: "Used in item listings and search results."

But actually it's used in listings, search results AND detail views of the contents itself.
In my opinion, this should be changed for all languages.

**Comment by vincentfretin** [comment]
Ok, what help message do you propose? If you change it, please do in both
Archetypes/ExtensibleMetadata.py:91 and
plone.app.dexterity/plone/app/dexterity/behaviors/metadata.py:75

**Comment by thet** [comment]
Maybe:
"Short text summarizing or describing the content. It is shown on the content view itself, in listings and search results."
"Kurzer Text, der den Inhalt zusammenfasst oder beschreibt. Die Beschreibung wird in der Detailansicht des Inhalts, in Auflistungen und Suchergebnissen angezeigt."

Does that make sense?

I don't know about any other languages...

**Comment by vincentfretin** [comment]
It makes sense.

Now that plone.app.dexterity is in the plone domain I see that in English we have for the description field for Archetypes "Description" and for Dexterity "Summary" (since 2008!). For all other languages, we have as default message Description because both Archetypes and Dexterity uses the same help_description msgid.
I found it weird we use Summary for the description field in the dexterity behavior, because Summary is not generic enough, what is a Summary for an Image?

**Comment by jensens** [comment]
I propose to go back to the more generic ``description``. 

In our projects I announce this also as a ``Teaser Text`` in our documentation. We rarely expose this on details view, only in listings / overview pages.

**Comment by vincentfretin** [comment]
+1 to go back to Description.
I'm ok with the help message from @thet too
