### ISSUE TITLE
Translation entry for "ModificationDate" is missing.

### ISSUE THREAD

**Issue by espenmn** [collective/plone.app.locales#231]
https://community.plone.org/t/collection-table-header-labels/6524/4

**Comment by vincentfretin** [comment]
The issue seems to be for all brain metadata on Plone 5.1 in the collection edit view and tabular view.
It was translated on Plone 4.3 and we don't have ModificationDate in the po file. 

In plone.app.collection 1.0.x (Plone 4.3), the vocabulary come from portal_atct.getMetadataDisplay (parts/packages/Products/ATContentTypes/tool/topic.py), the messages was extracted from CMFPlone/profiles/default/portal_atct.xml friendlyName attributes. 

In Plone 5.1, this is plone.app.contenttypes and it uses plone.app.contenttypes.metadatafields vocabulary. (plone.app.contenttypes/plone/app/contenttypes/behaviors/collection.py MetaDataFieldsVocabulary) The implementation here is really basic indeed. A correct correction should be to use the title coming from plone.app.querystring/plone/app/querystring/profiles/default/registry.xml which should be the same as Plone 4.3 and are already translated.

This is actually a known issue since 16 Feb 2015! https://github.com/plone/plone.app.contenttypes/issues/211
