### ISSUE TITLE
Updates for Plone 6.0

### ISSUE THREAD

**Issue by mauritsvanrees** [collective/plone.app.locales#315]
- Some `pot` files can probably be removed. `atcontenttypes.pot` should no longer be needed.
- But today I saw that `plone.app.content` uses the [`atcontenttypes` message factory](https://github.com/plone/plone.app.content/blob/3.8.7/plone/app/content/browser/constraintypes.py#L34-L47), so that would need to be changed.
- `atreferencebrowserwidget.pot` can be removed.
- [`plone-generated.pot`](`https://github.com/collective/plone.app.locales/blob/master/plone/app/locales/locales/plone-generated.pot) seems unused. And apparently it confuses people, because it has been translated to [Slovenian](https://github.com/collective/plone.app.locales/blob/master/plone/app/locales/locales/sl/LC_MESSAGES/plone-generated.po).
- Maybe the [`locales-addons` directory](https://github.com/collective/plone.app.locales/tree/master/plone/app/locales/locales-addons) can be removed. Currently it only contains translations for `plone.app.ldap`. This add-on does not see many [changes](https://github.com/plone/plone.app.ldap/blob/master/CHANGES.rst) and seems not yet compatible with Plone 5. In my part of the community this add-on is not used anymore. (But maybe others love it.)
- The [`locales-42` directory](https://github.com/collective/plone.app.locales/tree/master/plone/app/locales/locales-42) should be merged to `locales`. Could be done now already. It is [activated on Plone 4.2](https://github.com/collective/plone.app.locales/blob/master/plone/app/locales/configure.zcml#L9-L10) and higher before loading the standard locales, so the translations here are always active. This is only for Dutch, so maybe I could do that myself.

There is no hurry for this. But it seems that it would be logical at some point to let master only be for Plone 6.

**Comment by vincentfretin** [comment]
For `atcontenttypes` and `atreferencebrowserwidget`, yes it can be deleted if Archetypes is really not supported anymore on Plone 6.

For the usage of `atcontenttypes` i18n domain inside `plone.app.content`, it was me that did that recently. I should probably have  duplicated the msgid in the plone domain instead for the long term, my bad. We should do that, it can be done for Plone 5.2.x

today `plone.pot` is created by extracting the messages from plone domain and merging both `plone-manual.pot` and `plone-generated.pot` see https://github.com/plone/buildout.coredev/blob/9b6ebc1318a0fa1deadea8c4b503e604eed591de/experimental/i18n.cfg#L145
Some messages in `plone-generated.pot` may still be used today but now extracted with i18ndude, we need to check each msgid  to see if it's still in the code base.

I removed the unused po files in Slovenian in https://github.com/collective/plone.app.locales/commit/32d02d2062a67cd907b47a069dbc7ebb0449c25a

For `locale-addons`, if `plone.app.ldap` is not used by anyone in Plone 6 I guess we can remove it.

For locales-42, are you sure it's for Plone 4.2 and higher? I think it was for Plone 4.2 and lower. I couldn't find back why we did this. If it's really 4.2 and lower, this can already be removed because master is not compatible with Plone 4.x.

**Comment by vincentfretin** [comment]
We can remove `plone.app.collection` too in Plone 6 (#218)

And we also probably need to add `zope.app.locales` dependency and zcml for Plone 6, see https://github.com/plone/Products.CMFPlone/pull/3091#issuecomment-698819440 cc @jensens

**Comment by erral** [comment]
With the Plone 6 pre-alpha release, we should at least create a branch for Plone 5.x and leave master for 6, right? This way, we can work on removing the unneeded files and rework the dependencies

**Comment by mauritsvanrees** [comment]
For me this sounds good.

**Comment by erral** [comment]
I created #330 to track down the changes needed to be done when branching plone.app.locales for Plone 6.
